# Specifies the project id in KB
project_id: 6

# Specifies the path to the DB file
db_file_path: 'C:\\Apache24\\htdocs\\kanboard\\data\\db.sqlite'

# translation_table does the following mapping:
# <minecraft IGN>:
#   column: <column name in KB project>
#   username: <username in KB>
# If any value changes, its needed to update this table and restart the server unless I implement config reload :D
translation_table:
  AWEJOKER:
    column: AWEJOKER
    username: AWEJOKER
  Arturke44:
    column: Arturke44
    username: Arturke44
  Bubblegum_Wolf:
    column: Bubblegum_Wolf
    username: Bubblegum_Wolf
  ColorMaestro:
    column: ColorMaestro
    username: ColorMaestro
  Cyber_Leaf:
    column: Cyber_Leaf
    username: Cyber_Leaf
  ElasticWaistband:
    column: ElasticWaistband
    username: ElasticWaistband
  Erwa94:
    column: Erwa94
    username: Erwa94
  Gazur1223:
    column: Gazur1223
    username: Gazur1223
  KoganeNoKenshi:
    column: KoganeNoKenshi
    username: KoganeNoKenshi
  MrSpy321:
    column: MrSpy321
    username: MrSpy321
  Picorims:
    column: Picorims
    username: Picorims
  RekNepZ:
    column: RekNepZ_HBK
    username: RekNepZ_HBK
  Russicat:
    column: Russicat
    username: Russicat
  Xoyjaz:
    column: Xoyjaz
    username: Xoyjaz
  XxTechnoAngelxX:
    column: XxTechnoAngelxX
    username: XxTechnoAngelxX
  evsh777:
    column: evsh777
    username: evsh777