name: TaskManager
version: ${project.version}
main: me.colormaestro.taskmanager.TaskManager
api-version: 1.15
authors: [ColorMaestro]
depend: [Holograms]
commands:
  tasks:
    description: Shows your or other player tasks.
    usage: Usage /<command> [player] or /<command> help
    permission: taskmanager.tasks
    permission-message: You don't have permission to viev tasks
  addtask:
    description: Adds new task.
    usage: Usage /addtask <IGN> <description>
    permission: taskmanager.addtask
    permission-message: You don't have permission to add task
  finishtask:
    description: Mark task as finished.
    usage: Usage /finishtask <id>
    permission: taskmanager.finishtask
    permission-message: You don't have permission to finish task
  approvetask:
    description: Approves the finished task.
    usage: Usage /approvetask <id> [force]
    permission: taskmanager.approvetask
    permission-message: You don't have permission to approve task
  visittask:
    description: Teleports player to the task workplace.
    usage: Usage /visittask <id>
    permission: taskmanager.visittask
    permission-message: You don't have permission to visit task
  returntask:
    description: Returns task back to given (unfinished) state.
    usage: Usage /returntask <id> [force]
    permission: taskmanager.returntask
    permission-message: You don't have permission to return task
  transfertask:
    description: Gives selected task to another player.
    usage: Usage /transfertask <id> <IGN>
    permission: taskmanager.transfertask
    permission-message: You don't have permission to transfer task
  taskinfo:
    description: Gets related task info in book.
    usage: Usage /taskinfo <id>
    permission: taskmanager.taskinfo
    permission-message: You don't have permission to obtain task info
  settaskplace:
    description: Sets the spawning point for the task.
    usage: Usage /settaskplace <id>
    permission: taskmanager.settaskplace
    permission-message: You don't have permission to set spawn position for task
  linkdiscord:
    description: Links discord account for notifications.
    usage: Usage /linkdiscord
    permission: taskmanager.linkdiscord
    permission-message: You don't have permission to link discord account
  establish:
    description: Establishes the Hologram where is summary of players tasks.
    usage: Usage /establish
    permission: taskmanager.establish
    permission-message: You don't have permission to establish task hologram